const Commands = {
    SEND_BROADCAST_REQUEST: 'SEND_BROADCAST_REQUEST',
    SEND_CREATE_SESSION_REQUEST: 'SEND_CREATE_SESSION_REQUEST',
    SEND_CREDENTIALS_REQUEST: 'SEND_CREDENTIALS_REQUEST',
    SET_CREDENTIALS: 'SET_CREDENTIALS'
};

module.exports = Commands;
